AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB table for tracking 40 instances in batch processing

Resources:
  CheckpointingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CheckpointingTable
      AttributeDefinitions:
        - AttributeName: InstanceIndex
          AttributeType: N
      KeySchema:
        - AttributeName: InstanceIndex
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref CheckpointingTable
