AWSTemplateFormatVersion: '2010-09-09'
Description: |
  This CloudFormation template creates a Lambda function that is sourced
  from an S3 object. The function is set up with a specific handler and role, 
  and runs with a Python 3.11 runtime with a 60-second timeout.

Parameters:
  LambdaSourceBucket:
    Description: Name of the S3 bucket containing the Lambda function code.
    Type: String
    Default: mj-aws-lambda-code-us-east-1  # Default bucket name

  LambdaCodeS3Key:
    Description: S3 key for the Lambda function code.
    Type: String
    Default: step1_LambdaForUpdatingSpotPrice.zip  # Default S3 key

Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lambda_for_updating_spot_price
      Handler: lambda_for_updating_spot_price.lambda_handler
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LambdaWithAdminAccess'
      Code:
        S3Bucket: !Ref LambdaSourceBucket
        S3Key: !Ref LambdaCodeS3Key
      Runtime: python3.11
      Timeout: 60


#AWSTemplateFormatVersion: '2010-09-09'
#Description: |
#  This CloudFormation template creates a Lambda function that is sourced
#  from an S3 object. The function is set up with a specific handler and role,
#  and runs with a Python 3.11 runtime with a 60-second timeout.
#
#Parameters:
#  LambdaSourceBucket:
#    Description: Name of the S3 bucket containing the Lambda function code.
#    Type: String
#    Default: mj-aws-lambda-code-us-east-1  # Default bucket name
#
#Resources:
#  MyLambdaFunction:
#    Type: AWS::Lambda::Function
#    Properties:
#      FunctionName: lambda_insert_spot_instances_price
#      Handler: lambda_insert_spot_instances_price.lambda_handler
#      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LambdaWithAdminAccess'
#      Code:
#        S3Bucket: !Ref LambdaSourceBucket
#        S3Key: step1_LambdaForUpdatingSpotPrice.zip
#      Runtime: python3.11
#      Timeout: 60
