AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to set up permissions and event rules for triggering a Step Function every 1 hour.'

Parameters:
  Region:
    Description: "The region for the resources"
    Type: "String"
    Default: "us-east-1"
  StateMachineArn:
    Description: "ARN of the State Machine to be invoked"
    Type: "String"

Resources:

  StepFunctionInvokePermission:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: "events.amazonaws.com"
          Action: "sts:AssumeRole"
      Policies:
      - PolicyName: InvokeStepFunctionPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: "states:StartExecution"
            Resource: !Ref StateMachineArn

  HourlyEventRule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: "Event Rule to start a Step Function execution every 1 hour."
      ScheduleExpression: "rate(30 minutes)"
      State: "ENABLED"
      Targets:
        - Arn: !Ref StateMachineArn
          RoleArn: !GetAtt StepFunctionInvokePermission.Arn
          Id: "HourlyTarget"
